// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// egcar_native_solve
Rcpp::List egcar_native_solve(Rcpp::List context, Rcpp::List state, Rcpp::List controls, bool group, bool verbose);
RcppExport SEXP _egcar_egcar_native_solve(SEXP contextSEXP, SEXP stateSEXP, SEXP controlsSEXP, SEXP groupSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type context(contextSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type controls(controlsSEXP);
    Rcpp::traits::input_parameter< bool >::type group(groupSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(egcar_native_solve(context, state, controls, group, verbose));
    return rcpp_result_gen;
END_RCPP
}
// egcar_native_block_product
Rcpp::NumericVector egcar_native_block_product(Rcpp::List C, Rcpp::IntegerVector edge_k, Rcpp::IntegerVector edge_l, Rcpp::List local, Rcpp::List position, Rcpp::NumericVector v);
RcppExport SEXP _egcar_egcar_native_block_product(SEXP CSEXP, SEXP edge_kSEXP, SEXP edge_lSEXP, SEXP localSEXP, SEXP positionSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type C(CSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type edge_k(edge_kSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type edge_l(edge_lSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type local(localSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type position(positionSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(egcar_native_block_product(C, edge_k, edge_l, local, position, v));
    return rcpp_result_gen;
END_RCPP
}
// egcar_native_group_norms
Rcpp::List egcar_native_group_norms(Rcpp::List left, Rcpp::List right, Rcpp::IntegerVector edge_k, Rcpp::IntegerVector edge_l, Rcpp::IntegerVector sizes);
RcppExport SEXP _egcar_egcar_native_group_norms(SEXP leftSEXP, SEXP rightSEXP, SEXP edge_kSEXP, SEXP edge_lSEXP, SEXP sizesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type right(rightSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type edge_k(edge_kSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type edge_l(edge_lSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sizes(sizesSEXP);
    rcpp_result_gen = Rcpp::wrap(egcar_native_group_norms(left, right, edge_k, edge_l, sizes));
    return rcpp_result_gen;
END_RCPP
}
// egcar_native_edge_errors
Rcpp::NumericVector egcar_native_edge_errors(Rcpp::List C, Rcpp::List truth);
RcppExport SEXP _egcar_egcar_native_edge_errors(SEXP CSEXP, SEXP truthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type C(CSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type truth(truthSEXP);
    rcpp_result_gen = Rcpp::wrap(egcar_native_edge_errors(C, truth));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_egcar_egcar_native_solve", (DL_FUNC) &_egcar_egcar_native_solve, 5},
    {"_egcar_egcar_native_block_product", (DL_FUNC) &_egcar_egcar_native_block_product, 6},
    {"_egcar_egcar_native_group_norms", (DL_FUNC) &_egcar_egcar_native_group_norms, 5},
    {"_egcar_egcar_native_edge_errors", (DL_FUNC) &_egcar_egcar_native_edge_errors, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_egcar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
