# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

egcar_native_solve <- function(context, state, controls, group, verbose = FALSE) {
    .Call(`_egcar_egcar_native_solve`, context, state, controls, group, verbose)
}

egcar_native_block_product <- function(C, edge_k, edge_l, local, position, v) {
    .Call(`_egcar_egcar_native_block_product`, C, edge_k, edge_l, local, position, v)
}

egcar_native_group_norms <- function(left, right, edge_k, edge_l, sizes) {
    .Call(`_egcar_egcar_native_group_norms`, left, right, edge_k, edge_l, sizes)
}

egcar_native_edge_errors <- function(C, truth) {
    .Call(`_egcar_egcar_native_edge_errors`, C, truth)
}
